In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("diabetes.csv")

In [4]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [8]:
cols_for_fill = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

for col in cols_for_fill:
   df[col] = df[col].replace(0, np.nan)

In [11]:
for col in cols_for_fill:
    df[col] = df[col].fillna(df.groupby("Outcome")[col].transform("median"))

In [12]:
df[cols_for_fill].isnull().sum()

Glucose          0
BloodPressure    0
SkinThickness    0
Insulin          0
BMI              0
dtype: int64

In [13]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,121.677083,72.389323,29.089844,141.753906,32.434635,0.471876,33.240885,0.348958
std,3.369578,30.464161,12.106039,8.890820,89.100847,6.880498,0.331329,11.760232,0.476951
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
25%,1.000000,99.750000,64.000000,25.000000,102.500000,27.500000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,28.000000,102.500000,32.050000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,169.500000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [21]:
X = df.drop("Outcome", axis = 1)
y =df["Outcome"]

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state = 15)

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [23]:
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
y_pred = dt_model.predict(X_test)

In [24]:
print("classification_report: \n ", classification_report(y_test, y_pred))
print("accuracy_score: ", accuracy_score(y_test, y_pred))
print("confusion_matrix: \n", confusion_matrix(y_test, y_pred))

classification_report:
                precision    recall  f1-score   support

           0       0.88      0.87      0.87        83
           1       0.68      0.70      0.69        33

    accuracy                           0.82       116
   macro avg       0.78      0.78      0.78       116
weighted avg       0.82      0.82      0.82       116

accuracy_score:  0.8189655172413793
confusion_matrix:
 [[72 11]
 [10 23]]

In [36]:
params = {
    "criterion": ["gini", "entropy", "log_loss"],
    "splitter": ["best", "random"],
    "max_depth":[3,5,7, None],
    "max_features": ["sqrt", "log2", 3, 5, 8]
}

In [37]:
from sklearn.model_selection import GridSearchCV

In [40]:
grid = GridSearchCV(estimator = DecisionTreeClassifier(), param_grid = params, cv = 3,verbose = 1, n_jobs = -1)

In [41]:
grid.fit(X_train, y_train)

Fitting 3 folds for each of 120 candidates, totalling 360 fits

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [3, 5, 7, None],
                         'max_features': ['sqrt', 'log2', 3, 5, 8],
                         'splitter': ['best', 'random']},
             verbose=1)

In [42]:
grid.best_params_

{'criterion': 'entropy',
 'max_depth': 7,
 'max_features': 'sqrt',
 'splitter': 'best'}

In [43]:
dt_model2 = DecisionTreeClassifier(criterion="entropy", max_depth= 7, max_features= 'sqrt', splitter= 'best')

In [44]:
dt_model2.fit(X_train, y_train)
y_pred2 = dt_model2.predict(X_test)
print("classification_report: \n ", classification_report(y_test, y_pred2))
print("accuracy_score: ", accuracy_score(y_test, y_pred2))
print("confusion_matrix: \n", confusion_matrix(y_test, y_pred2))

classification_report:
                precision    recall  f1-score   support

           0       0.87      0.86      0.86        83
           1       0.65      0.67      0.66        33

    accuracy                           0.80       116
   macro avg       0.76      0.76      0.76       116
weighted avg       0.80      0.80      0.80       116

accuracy_score:  0.8017241379310345
confusion_matrix:
 [[71 12]
 [11 22]]

In [46]:
import joblib
joblib.dump(dt_model, 'diabetes_model.pkl')

['diabetes_model.pkl']